- id: '1771029405189'
  alias: Turn off lights when leave
  description: ''
  triggers:
  - trigger: zone
    entity_id: device_tracker.normans_iphone
    zone: zone.home
    event: leave
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      label_id: light
  - action: switch.turn_off
    metadata: {}
    target:
      label_id: light
    data: {}
  mode: single
- id: '1771029768568'
  alias: Turn on the lights when I get home
  description: ''
  triggers:
  - trigger: zone
    entity_id: device_tracker.normans_iphone
    zone: zone.home
    event: enter
  conditions:
  - condition: sun
    after: sunset
    before: sunrise
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      label_id: lamp
    data: {}
  mode: single
- id: '1771035333639'
  alias: 'ON: Low Light'
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions:
  - condition: zone
    entity_id: person.norman_ramirez
    zone: zone.home
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      label_id: lamp
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id:
      - scene.lr_dim
      - scene.mb_dim
    data: {}
  mode: single
- id: '1771035434876'
  alias: Turn off the lights at 10pm
  description: ''
  triggers:
  - trigger: time
    at: '22:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      label_id: light
    data: {}
  - action: switch.turn_off
    metadata: {}
    target:
      label_id: light
    data: {}
  mode: single
- id: '1771085107419'
  alias: 'MB: Idle TV'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.playstation_4_2
    to:
    - 'off'
    - idle
    - unknown
    - unavailable
    - paused
    - standby
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.mb_dim
  mode: single
