- id: '1771029405189'
  alias: Turn off lights when leave
  description: ''
  triggers:
  - trigger: zone
    entity_id: device_tracker.normans_iphone
    zone: zone.home
    event: leave
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      label_id: light
  - action: switch.turn_off
    metadata: {}
    target:
      label_id: light
    data: {}
  mode: single
- id: '1771029768568'
  alias: Turn on the lights when I get home
  description: ''
  triggers:
  - trigger: zone
    entity_id: device_tracker.normans_iphone
    zone: zone.home
    event: enter
  conditions:
  - condition: sun
    after: sunset
    before: sunrise
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      label_id: lamp
    data: {}
  mode: single
- id: '1771035333639'
  alias: 'ON: Low Light'
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions:
  - condition: zone
    entity_id: person.norman_ramirez
    zone: zone.home
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      label_id: lamp
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id:
      - scene.lr_dim
      - scene.mb_dim
    data: {}
  mode: single
- id: '1771035434876'
  alias: Turn off the lights at 10pm
  description: ''
  triggers:
  - trigger: time
    at: '22:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      label_id: light
    data: {}
  - action: switch.turn_off
    metadata: {}
    target:
      label_id: light
    data: {}
  mode: single
- id: '1771080002196'
  alias: Night Walk
  description: ''
  triggers:
  - type: turned_on
    device_id: c9241b2a79b5872396edc88d8a8160e0
    entity_id: f1fe8a99064df60f4b021c01d764c19d
    domain: switch
    trigger: device
  - type: turned_on
    device_id: 0997ecdf6454a32c69765340adf54399
    entity_id: bdd68628b5f07cb1f6016ec75c64640d
    domain: switch
    trigger: device
  conditions:
  - condition: time
    after: 00:00:00
    before: 05:00:00
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.lr_lamp
    data: {}
  mode: single
- id: '1771080220247'
  alias: 'Night Walk: Off'
  description: ''
  triggers:
  - type: turned_off
    device_id: c9241b2a79b5872396edc88d8a8160e0
    entity_id: f1fe8a99064df60f4b021c01d764c19d
    domain: switch
    trigger: device
  - type: turned_off
    device_id: 0997ecdf6454a32c69765340adf54399
    entity_id: bdd68628b5f07cb1f6016ec75c64640d
    domain: switch
    trigger: device
  conditions:
  - condition: time
    after: 00:00:00
    before: 05:00:00
    weekday:
    - sat
    - fri
    - thu
    - wed
    - tue
    - mon
    - sun
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.lr_lamp
    data: {}
  mode: single
- id: '1771080380126'
  alias: 'Auto: Daylight'
  description: ''
  triggers:
  - type: turned_on
    device_id: 90f371f2015c3e8e8e1f73977d42827c
    entity_id: 0e8205bb9cb3e4e6ccc528fa15e846e6
    domain: light
    trigger: device
  - type: turned_on
    device_id: 2a0dfd3e1e10fa72be1d711b824a5815
    entity_id: 5fbf804376aa44a4d077a35209f19bf8
    domain: light
    trigger: device
  conditions:
  - condition: sun
    before: sunset
    after: sunrise
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.mb_day_light
    data: {}
  mode: single
- id: '1771080435893'
  alias: 'MB: Auto Dim'
  description: ''
  triggers:
  - type: turned_on
    device_id: 90f371f2015c3e8e8e1f73977d42827c
    entity_id: 0e8205bb9cb3e4e6ccc528fa15e846e6
    domain: light
    trigger: device
  - type: turned_on
    device_id: 2a0dfd3e1e10fa72be1d711b824a5815
    entity_id: 5fbf804376aa44a4d077a35209f19bf8
    domain: light
    trigger: device
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.mb_dim
  mode: single
- id: '1771080638853'
  alias: 'LR: Auto Daylight'
  description: ''
  triggers:
  - type: turned_on
    device_id: 183d57d42c40ec874525987b0a79b6f5
    entity_id: 09b695bc77f99b2a575df1aca961ac1f
    domain: light
    trigger: device
  - type: turned_on
    device_id: e17cf3f460205b07d4b533b30fea5a1d
    entity_id: 1c89c58db683b5fd68cbb9b4ad4f43aa
    domain: light
    trigger: device
  conditions:
  - condition: sun
    before: sunset
    after: sunrise
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id:
      - scene.lr_day_light
    data: {}
  mode: single
- id: '1771080699733'
  alias: 'LR: Auto Dim'
  description: ''
  triggers:
  - type: turned_on
    device_id: 183d57d42c40ec874525987b0a79b6f5
    entity_id: 09b695bc77f99b2a575df1aca961ac1f
    domain: light
    trigger: device
  - type: turned_on
    device_id: e17cf3f460205b07d4b533b30fea5a1d
    entity_id: 1c89c58db683b5fd68cbb9b4ad4f43aa
    domain: light
    trigger: device
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id:
      - scene.lr_dim
  mode: single
- id: '1771085036395'
  alias: 'MB: TV Playing'
  description: ''
  triggers:
  - device_id: 83186c58b95a22f66a196ef8e678ae49
    domain: media_player
    entity_id: 8c1dde29ae8722b68b2e0cda3ddfffbb
    type: playing
    trigger: device
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.redish
    data: {}
  mode: single
- id: '1771085107419'
  alias: 'MB: Idle TV'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.playstation_4_2
    to:
    - 'off'
    - idle
    - unknown
    - unavailable
    - paused
    - standby
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.mb_dim
  mode: single
- id: '1771090342172'
  alias: 'LR: Playing TV'
  description: ''
  triggers:
  - device_id: 27133817da8e53760a3900ea945e9492
    domain: media_player
    entity_id: 48bb63963012218cc0f83589c7870aab
    type: turned_on
    trigger: device
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.lr_redish
    data: {}
  mode: single
- id: '1771090484563'
  alias: 'LR: Pausing TV'
  description: ''
  triggers:
  - device_id: 27133817da8e53760a3900ea945e9492
    domain: media_player
    entity_id: 48bb63963012218cc0f83589c7870aab
    type: turned_off
    trigger: device
  conditions:
  - condition: sun
    before: sunrise
    after: sunset
  actions:
  - action: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.lr_dim
    data: {}
  mode: single
