automation:
  - id: '1771080638853'
    alias: 'LR: Auto Daylight'
    description: ''
    triggers:
      - trigger: state
        entity_id:
          - light.living
          - light.dining
        to: 'on'
    conditions:
      - condition: numeric_state
        entity_id: sensor.light_sensor_samsung_illuminance
        above: 24
    actions:
      - action: scene.turn_on
        target:
          entity_id:
            - scene.lr_day_light
    mode: single

  - id: '1771080699733'
    alias: 'LR: Auto Dim'
    description: ''
    triggers:
      - trigger: state
        entity_id:
          - light.living
          - light.dining
        to: 'on'
    conditions:
      - condition: numeric_state
        entity_id: sensor.light_sensor_samsung_illuminance
        below: 25
    actions:
      - action: scene.turn_on
        target:
          entity_id:
            - scene.lr_dim
    mode: single

  - id: '1771090342172'
    alias: 'LR: Playing TV'
    description: ''
    triggers:
      - trigger: state
        entity_id:
          - media_player.samsung
          - media_player.samsung_cast
        from: 'off'
        not_to:
          - 'unavailable'
          - 'unknown'
    conditions:
      - condition: sun
        before: sunrise
        after: sunset
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.lr_redish
    mode: single

  - id: '1771090484563'
    alias: 'LR: Pausing TV'
    description: ''
    triggers:
      - trigger: state
        entity_id:
          - media_player.samsung
          - media_player.samsung_cast
        to: 'off'
        for: '00:00:30'
    conditions:
      - condition: sun
        before: sunrise
        after: sunset
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.lr_dim
    mode: single

scene:
  - id: '1771077904382'
    name: 'LR: Redish'
    icon: mdi:fire-circle
    entities:
      light.living:
        state: 'on'
        brightness: 255
        hs_color: [9, 100]
      light.dining:
        state: 'on'
        brightness: 255
        hs_color: [9, 100]

  - id: '1771077995810'
    name: 'LR: Bluish'
    icon: mdi:shield-moon
    entities:
      light.dining:
        state: 'on'
        brightness: 255
        hs_color: [217, 100]
      light.living:
        state: 'on'
        brightness: 255
        hs_color: [217, 100]

  - id: '1771078366080'
    name: 'LR: Day Light'
    icon: mdi:shield-sun
    entities:
      light.living:
        state: 'on'
        brightness: 255
        color_temp_kelvin: 6500
      light.dining:
        state: 'on'
        brightness: 255
        color_temp_kelvin: 6500

  - id: '1771079390602'
    name: 'LR: Dim'
    icon: mdi:lightbulb-night
    entities:
      light.dining:
        state: 'on'
        brightness: 76
        color_temp_kelvin: 2000
      light.living:
        state: 'on'
        brightness: 76
        color_temp_kelvin: 2000
