automation:
  - id: '1771080380126'
    alias: 'Auto: Daylight'
    description: ''
    triggers:
      - trigger: state
        entity_id:
          - light.mb_led_one
          - light.mb_led_two
        to: 'on'
    conditions:
      - condition: sun
        before: sunset
        after: sunrise
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.mb_day_light
    mode: single

  - id: '1771080435893'
    alias: 'MB: Auto Dim'
    description: ''
    triggers:
      - trigger: state
        entity_id:
          - light.mb_led_one
          - light.mb_led_two
        to: 'on'
    conditions:
      - condition: sun
        before: sunrise
        after: sunset
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.mb_dim
    mode: single

  - id: '1771085036395'
    alias: 'MB: TV Playing'
    description: ''
    triggers:
      - trigger: state
        entity_id: media_player.playstation_4_2
        to: 'playing'
    conditions:
      - condition: sun
        before: sunrise
        after: sunset
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.redish
    mode: single

  - id: '1771085107419'
    alias: 'MB: Idle TV'
    triggers:
      - trigger: state
        entity_id:
          - media_player.playstation_4_2
        to:
          - 'off'
          - idle
          - unknown
          - unavailable
          - paused
          - standby
    conditions:
      - condition: sun
        before: sunrise
        after: sunset
    actions:
      - action: scene.turn_on
        target:
          entity_id: scene.mb_dim
    mode: single
