automation:
  - id: '1771035434876'
    alias: Turn off the lamps at 10pm
    triggers:
      - trigger: time
        at: '22:00:00'
    actions:
      - action: switch.turn_off
        target:
          label_id: socket
    mode: single
